Merge versioned branches into main (#168)
* Revert "Upgraded to dbt-core 1.4. (#146)"

This reverts commit 3db05eb15d351d050caa52e50a589b1b82bcd6e2.

* Fix version bumping

* Migration bump2version (unmaintained) to bump-my-version
* Import `bumpversion.cfg` from `dbt-snowflake`
* Convert `bumpversion.cfg` to `bumpversion.toml`
* Fix a few incorrect version labels

* Remove macos and windows as integration targets

* Fix requirements conflict between dbt 1.2 and tox

* Bump version to 1.3

* Upgraded to dbt-core 1.4. (#146)

* Upgraded to dbt-core 1.4.

* Updated CHANGELOG.

* Fixed policy fields definitions for mariadb and mysql5.

* Replaced deprecated dbt.exceptions.raise_compiler_error() with dbt.exceptions.CompilationError.

* Now using dbt.exceptions.DbtDatabaseError insead of dbt.exceptions.DatabaseException.

* Update version

* Update changelog

---------

Co-authored-by: Doug Beatty <doug.beatty@dbtlabs.com>

* Bump version to 1.5

* Update dbt-core to 1.5 and implement support for model contracts (#163)

Update dbt-core to 1.5.9 and implement support for constraints
* Update changelog
* Fix unit test error
     - The error was: `AttributeError: 'Namespace' object has no attribute 'MACRO_DEBUGGING'`
* Allow Unix socket connection rather than just TCP (#165)

* Support Black & MyPy pre-commit hooks (#167)

* Add black and mypy as pre-commit hooks

* Run black formatter on all files

* Add MyPy configuration & make tweaks and ignore errors to make MyPy pass

* Add .git-blame-ignore-revs to ignore `black` changes in git blame

* Update changelog

* Run black formatter on all files

* Add black commit to .git-blame-ignore-revs

* Run black formatter on all files

* Add black commit to .git-blame-ignore-revs

* Fix MyPy & black errors

* Make the `database` config field nullable again

* Fix mypy

* Bump version to 1.6

* Bump version to 1.7

* Fix import error

---------

Co-authored-by: Luke <lpezet@gmail.com>
Co-authored-by: Doug Beatty <doug.beatty@dbtlabs.com>